name: Deploy

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy-client:
    name: Deploy client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build client
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Transfer files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: va1b3.ftp.infomaniak.com
          username: va1b3_binch
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: client/dist
          server-dir: client
          dangerous-clean-slate: true

  deploy-server:
    name: Deploy server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        working-directory: server
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress --no-suggest

      - name: Transfer files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: va1b3.ftp.infomaniak.com
          username: va1b3_binch
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: server
          server-dir: server
          dangerous-clean-slate: true
