name: Node CI

on:
  push:
    paths:
      - client/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install and build
        working-directory: client
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
